"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['EvernotePalmMemoImporter.py']
# is the following line even necessary? For a while I forgot PDNP.py and it still worked...
# maybe it figures out Python library dependencies automatically?
DATA_FILES = ['en_palmimport.py', 'EvernoteManager.py', 'PalmDesktopNoteParser.py', 'lib']
PLIST = { 'CFBundleIdentifier' : 'com.maddogsw.evernote-palm-importer',
          'CFBundleShortVersionString': '1.0.1' }
OPTIONS = {'argv_emulation': True,
           'plist': PLIST }

setup(
    app = APP,
    data_files = DATA_FILES,
    options = {'py2app': OPTIONS},
    setup_requires = ['py2app'],
)
